service: intuitive-math
provider:
  name: aws
  runtime: nodejs6.10
  credentials: ${file(../intuimath-credentials/config/app/env.yml):credentials}
functions:
  api:
    handler: prodLambda.handler
    environment:
      NODE_ENV: production
    events:
      - http:
          path: /
          method: ANY
