service: intuitive-math
plugins:
 - serverless-apigw-binary
 - serverless-apigwy-binary
custom:
   apigwBinary:
     type:
       - 'image/jpeg'
       - 'image/png'
       - 'image/x-icon'
provider:
  name: aws
  runtime: nodejs6.10
  credentials: ${file(../intuimath-credentials/config/app/env.yml):credentials}
functions:
  api:
    handler: prodLambda.handler
    environment:
      NODE_ENV: production
    events:
      - http:
          path: /
          method: ANY
          contentHandling: CONVERT_TO_BINARY
