service: nntree-app
provider:
  name: aws
  runtime: nodejs6.10
  credentials: ${file(../nntree-config/config/app/env.yml):credentials}
functions:
  api:
    handler: lambda.handler
    environment:
      NODE_ENV: production
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY